import React, { useState } from "react";
import { Link } from "react-router-dom";
import "./Support.css";
import { useAppData } from "../../Data/BackEnd Data/FetchBackEndData";
import { phoneNumber, whatsappLink1 } from "../../Data/BrandData";

import {
  quickActions,
  faqCategories,
  faqs,
  supportCards,
  supportProcess,
  supportPromises,
  supportServices,
} from "../../Data/Page Data/SupportPageData";
import { submitWeb3Form } from "../../Components/WebFormFunction/WebFormFunction";
import { toast } from "react-toastify";
import { askWhatsappConfirmation } from "../../Components/Whatsapp Confirmation/WhatsappConfirmation";
// import SupportForm from "../../Components/Support Form/SupportForm";
import { SupportSEO } from "../../Data/AllPageSEOs";

const Support = () => {
  const { websiteData, loading } = useAppData();
  let counters = {};
  if (!loading) {
    counters = websiteData.counters;
  }

  const [formLoading, setFormLoading] = useState(false);

  const [formData, setFormData] = useState({
    fullName: "",
    email: "",
    phone: "",
    company: "",
    businessType: "",
    service: "",
    budget: "",
    timeline: "",
    priority: "Normal",
    message: "",
    agree: false,
    EmailFrom: "Support Page Form",
  });
  const [errors, setErrors] = useState({});
  // const [success, setSuccess] = useState(false);

  const handleChange = (e) => {
    const { name, value, type, checked } = e.target;

    setFormData((prev) => ({
      ...prev,
      [name]: type === "checkbox" ? checked : value,
    }));
  };

  const maxCharacters = 500;

  const validateForm = () => {
    const newErrors = {};

    if (!formData.fullName.trim()) {
      newErrors.fullName = "Full name is required.";
    }

    if (!formData.email.trim()) {
      newErrors.email = "Email is required.";
    } else if (
      !/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i.test(formData.email)
    ) {
      newErrors.email = "Enter a valid email.";
    }

    if (!formData.phone.trim()) {
      newErrors.phone = "Phone number is required.";
    }

    if (!formData.service) {
      newErrors.service = "Please select a service.";
    }

    if (!formData.message.trim()) {
      newErrors.message = "Please describe your project.";
    }

    if (!formData.agree) {
      newErrors.agree = "Please accept Privacy Policy & Terms.";
    }

    setErrors(newErrors);

    return Object.keys(newErrors).length === 0;
  };
  const handleSubmit = async (event) => {
    event.preventDefault();

    if (!validateForm()) return;

    setFormLoading(true);

    const formDataUpdated = new FormData(event.target);
    formDataUpdated.append("from_name", "NexGen Web Designs");
    formDataUpdated.append("subject", "New Pricing Enquiry Form");

    const response = await submitWeb3Form(formDataUpdated);
    if (response.success) {
      setFormLoading(false);
      toast.success("Your request has been submitted successfully.");

      const message = `

    ━━━━━━━━━━━━━━━━━━
    NEW PROJECT ENQUIRY
    ━━━━━━━━━━━━━━━━━━

    Submitted From
    Home Page - Support / Project Enquiry Form

    ━━━━━━━━━━━━━━━━━━
    CLIENT INFORMATION
    ━━━━━━━━━━━━━━━━━━

    Name       : ${formData.fullName}

    Email      : ${formData.email}

    Phone      : ${formData.phone}

    Company    : ${formData.company}

    Business   : ${formData.businessType}

    ━━━━━━━━━━━━━━━━━━
    PROJECT REQUIREMENTS
    ━━━━━━━━━━━━━━━━━━

    Service    : ${formData.service}

    Budget     : ${formData.budget}

    Timeline   : ${formData.timeline}

    Priority   : ${formData.priority}

    ━━━━━━━━━━━━━━━━━━
    PROJECT DESCRIPTION
    ━━━━━━━━━━━━━━━━━━

    ${formData.message}

    ━━━━━━━━━━━━━━━━━━
    Submitted On
    ${new Date().toLocaleString("en-IN")}

    ━━━━━━━━━━━━━━━━━━
    Generated by
    NexGen Web Designs Website

    `;

      const url = `https://wa.me/918331889448?text=${encodeURIComponent(message)}`;

      setTimeout(async () => {
        await askWhatsappConfirmation(url);

        setFormLoading(false);

        setFormData({
          fullName: "",

          email: "",

          phone: "",

          company: "",

          businessType: "",

          service: "",

          budget: "",

          timeline: "",

          priority: "Normal",

          message: "",

          agree: false,
        });
      }, 1000);
    }
  };
  return (
    <main className="support-page">
      {/* ================= HERO ================= */}
      {SupportSEO}
      <section className="support-hero">
        <div className="support-grid"></div>

        <div className="support-blur blur-one"></div>
        <div className="support-blur blur-two"></div>

        <div className="container">
          <div className="support-wrapper">
            {/* LEFT */}

            <div className="support-left">
              <div className="support-live">
                <span className="live-dot"></span>
                Support Team Online
              </div>

              <h1>
                We're Here To Help Your Business
                <span>Grow Faster.</span>
              </h1>

              <p>
                Whether you need a new website, technical support, website
                maintenance, hosting assistance or simply have a question, our
                team is ready to help you.
              </p>

              {/* Search */}

              {/* <div className="support-search">
                <i className="fa-solid fa-magnifying-glass"></i>

                <input
                  type="text"
                  placeholder="Search support articles or ask a question..."
                />

                <button>Search</button>
              </div> */}

              {/* Buttons */}

              <div className="support-buttons">
                <Link to="/contact" className="support-primary">
                  Contact Support
                  <i className="fa-solid fa-arrow-right"></i>
                </Link>

                <a
                  href={whatsappLink1}
                  target="_blank"
                  rel="noreferrer"
                  className="support-secondary"
                >
                  <i className="fa-brands fa-whatsapp"></i>
                  WhatsApp
                </a>
              </div>
            </div>

            {/* RIGHT */}

            <div className="support-right">
              <div className="support-dashboard">
                <div className="dashboard-top">
                  <span>
                    <i className="fa-solid fa-headset"></i>
                    NexGen Support Center
                  </span>

                  <div className="status-online">Online</div>
                </div>

                {/* Floating cards */}

                <div className="support-card-list">
                  {supportCards.map((item, index) => (
                    <div
                      className={`support-info-card card-${index + 1}`}
                      key={index}
                    >
                      <div
                        className="support-icon"
                        style={{
                          background: item.color,
                        }}
                      >
                        <i className={item.icon}></i>
                      </div>

                      <div>
                        <h4>{item.title}</h4>

                        <p>{item.text}</p>
                      </div>
                    </div>
                  ))}
                </div>

                {/* Bottom Stats */}

                <div className="support-stats">
                  <div>
                    <h3>98%</h3>

                    <p>Client Satisfaction</p>
                  </div>

                  <div>
                    <h3>10 Min</h3>

                    <p>Average Response</p>
                  </div>

                  <div>
                    <h3>24/7</h3>

                    <p>Online Assistance</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ================= QUICK ACTIONS ================= */}

      <section className="support-actions">
        <div className="container">
          <div className="support-section-heading">
            <span>SUPPORT OPTIONS</span>

            <h2>Choose The Fastest Way To Reach Us</h2>

            <p>
              Select your preferred support channel. Our team is committed to
              providing prompt, professional and reliable assistance.
            </p>
          </div>

          <div className="actions-grid">
            {quickActions.map((item, index) => (
              <div className="action-card" key={index}>
                <div className="action-icon">
                  <i className={item.icon}></i>
                </div>

                <h4>{item.title}</h4>

                <p>{item.desc}</p>

                <Link to={item.link}>
                  Get Started
                  <i className="fa-solid fa-arrow-right"></i>
                </Link>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* <SupportForm /> */}
      <section className="support-services">
        <div className="container">
          <div className="support-section-heading">
            <span>SUPPORT CATEGORIES</span>

            <h2>What Can We Help You With?</h2>

            <p>
              Select the category that best matches your requirement. Our
              experts will connect you with the right solution quickly.
            </p>
          </div>

          <div className="support-services-grid">
            {supportServices.map((service, index) => (
              <div className="support-service-card" key={index}>
                <span className="service-badge">{service.badge}</span>

                <div className="service-icon">
                  <i className={service.icon}></i>
                </div>

                <h3>{service.title}</h3>

                <p>{service.desc}</p>

                <Link to={`tel:${phoneNumber}`}>
                  Get Help
                  <i className="fa-solid fa-arrow-right ms-3"></i>
                </Link>
              </div>
            ))}
          </div>
        </div>
      </section>
      {/* ==========================================================
      CONTACT SUPPORT FORM
========================================================== */}

      <section className="support-contact">
        <div className="container">
          <div className="support-section-heading">
            <span>CONTACT OUR TEAM</span>

            <h2>Tell Us About Your Project</h2>

            <p>
              Fill out the form below and our team will review your request
              before contacting you with the best solution for your business.
            </p>
          </div>

          <div className="support-form-wrapper">
            {/* LEFT INFO */}

            <div className="support-form-info">
              <div className="support-info-box">
                <div className="info-icon">
                  <i className="fa-solid fa-headset"></i>
                </div>

                <div>
                  <h4>Premium Support</h4>

                  <p>
                    Talk directly with experienced web developers and designers.
                  </p>
                </div>
              </div>

              <div className="support-info-box">
                <div className="info-icon">
                  <i className="fa-solid fa-clock"></i>
                </div>

                <div>
                  <h4>Fast Response</h4>

                  <p>
                    We usually respond within a few hours during business days.
                  </p>
                </div>
              </div>

              <div className="support-info-box">
                <div className="info-icon">
                  <i className="fa-solid fa-shield"></i>
                </div>

                <div>
                  <h4>100% Confidential</h4>

                  <p>Your project information remains private and secure.</p>
                </div>
              </div>
            </div>

            {/* FORM */}

            <div className="support-form-card">
              <form onSubmit={handleSubmit}>
                <div className="support-grid-2">
                  <div className="support-field">
                    <label>
                      Full Name <span className="ms-1 text-danger">*</span>
                    </label>

                    <input
                      type="text"
                      name="fullName"
                      value={formData.fullName}
                      onChange={handleChange}
                      disabled={formLoading}
                      placeholder="John Doe"
                    />
                    {errors.fullName && (
                      <p className="error-text">{errors.fullName}</p>
                    )}
                  </div>

                  <div className="support-field">
                    <label>
                      Email Address <span className="ms-1 text-danger">*</span>
                    </label>

                    <input
                      type="email"
                      name="email"
                      value={formData.email}
                      onChange={handleChange}
                      disabled={formLoading}
                      placeholder="example@email.com"
                    />
                    {errors.email && (
                      <p className="error-text">{errors.email}</p>
                    )}
                  </div>
                </div>

                <div className="support-grid-2">
                  <div className="support-field">
                    <label>
                      Phone Number <span className="ms-1 text-danger">*</span>
                    </label>

                    <input
                      type="tel"
                      name="phone"
                      value={formData.phone}
                      onChange={handleChange}
                      disabled={formLoading}
                      placeholder="+91 XXXXX XXXXX"
                    />
                    {errors.phone && (
                      <p className="error-text">{errors.phone}</p>
                    )}
                  </div>

                  <div className="support-field">
                    <label>
                      Company Name <span className="ms-1 text-danger">*</span>
                    </label>

                    <input
                      type="text"
                      name="company"
                      value={formData.company}
                      onChange={handleChange}
                      disabled={formLoading}
                      placeholder="Business Name"
                    />
                  </div>
                  <div className="support-field d-none">
                    <label>Email From</label>

                    <input
                      type="text"
                      name="EmailFrom"
                      value={formData.EmailFrom}
                      onChange={handleChange}
                      disabled={formLoading}
                      placeholder="Email From"
                    />
                  </div>
                </div>

                <div className="support-grid-2">
                  <div className="support-field">
                    <label>Business Type </label>

                    <select
                      name="businessType"
                      value={formData.businessType}
                      disabled={formLoading}
                      onChange={handleChange}
                    >
                      <option value="">Select</option>

                      <option>Startup</option>

                      <option>Small Business</option>

                      <option>Restaurant</option>

                      <option>Real Estate</option>

                      <option>Medical</option>

                      <option>Education</option>

                      <option>E-Commerce</option>

                      <option>Agency</option>

                      <option>Other</option>
                    </select>
                  </div>

                  <div className="support-field">
                    <label>
                      Service Required{" "}
                      <span className="ms-1 text-danger">*</span>
                    </label>

                    <select
                      name="service"
                      value={formData.service}
                      disabled={formLoading}
                      onChange={handleChange}
                    >
                      <option value="">Select</option>

                      <option>Website Design</option>

                      <option>Website Development</option>

                      <option>Website Redesign</option>

                      <option>SEO</option>

                      <option>Hosting</option>

                      <option>Maintenance</option>

                      <option>Bug Fixing</option>
                    </select>
                    {errors.service && (
                      <p className="error-text">{errors.service}</p>
                    )}
                  </div>
                </div>

                <div className="support-grid-3">
                  <div className="support-field">
                    <label>Budget</label>

                    <select
                      name="budget"
                      value={formData.budget}
                      disabled={formLoading}
                      onChange={handleChange}
                    >
                      <option value="">Select</option>

                      <option>₹5k - ₹10k</option>

                      <option>₹10k - ₹25k</option>

                      <option>₹25k - ₹50k</option>

                      <option>₹50k+</option>
                    </select>
                  </div>

                  <div className="support-field">
                    <label>Timeline</label>

                    <select
                      name="timeline"
                      value={formData.timeline}
                      disabled={formLoading}
                      onChange={handleChange}
                    >
                      <option value="">Select</option>

                      <option>Immediately</option>

                      <option>1 Week</option>

                      <option>2 Weeks</option>

                      <option>1 Month</option>

                      <option>Flexible</option>
                    </select>
                  </div>

                  <div className="support-field">
                    <label>Priority</label>

                    <select
                      name="priority"
                      value={formData.priority}
                      onChange={handleChange}
                      disabled={formLoading}
                    >
                      <option>Normal</option>

                      <option>High</option>

                      <option>Urgent</option>
                    </select>
                  </div>
                </div>

                <div className="support-field">
                  <label>
                    Project Details <span className="ms-1 text-danger">*</span>
                  </label>

                  <textarea
                    rows="6"
                    name="message"
                    value={formData.message}
                    onChange={handleChange}
                    maxLength={maxCharacters}
                    disabled={formLoading}
                    placeholder="Describe your project..."
                  />

                  <div className="character-counter">
                    {formData.message.length}/{maxCharacters}
                  </div>
                  {errors.message && (
                    <p className="error-text">{errors.message}</p>
                  )}
                </div>

                <div className="support-checkbox">
                  <input
                    type="checkbox"
                    id="agree"
                    name="agree"
                    disabled={formLoading}
                    checked={formData.agree}
                    onChange={handleChange}
                  />

                  <label htmlFor="agree">
                    I agree to the Privacy Policy and Terms & Conditions.
                  </label>
                </div>
                {errors.agree && <p className="error-text">{errors.agree}</p>}

                <div className="support-submit">
                  <button type="submit" disabled={formLoading}>
                    {formLoading ? (
                      <>
                        <i className="fa-solid fa-spinner fa-spin"></i>
                        Sending...
                      </>
                    ) : (
                      <>
                        Submit Support Request
                        <i className="fa-solid fa-paper-plane"></i>
                      </>
                    )}
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </section>
      <section className="support-process">
        <div className="container">
          <div className="support-section-heading">
            <span>HOW IT WORKS</span>

            <h2>Our Support Process</h2>

            <p>
              Every support request follows a structured workflow, ensuring
              faster communication, clear expectations, and professional project
              management.
            </p>
          </div>

          <div className="support-process-grid">
            {supportProcess.map((item, index) => (
              <div className="process-card" key={index}>
                <div className="process-number">{item.number}</div>

                <div className="process-icon">
                  <i className={item.icon}></i>
                </div>

                <h3>{item.title}</h3>

                <p>{item.text}</p>
              </div>
            ))}
          </div>
        </div>
      </section>
      {/* =====================================================
      KNOWLEDGE CENTER
===================================================== */}

      <section className="knowledge-center">
        <div className="container">
          <div className="support-section-heading">
            <span>KNOWLEDGE CENTER</span>

            <h2>Find Answers Instantly</h2>

            <p>
              Browse our most common questions and support categories before
              contacting our team.
            </p>
          </div>

          <div className="knowledge-search">
            <i className="fa-solid fa-magnifying-glass"></i>

            <input type="text" placeholder="Search help articles..." />
          </div>

          <div className="knowledge-category-grid">
            {faqCategories.map((item, index) => (
              <div className="knowledge-category-card" key={index}>
                <div
                  className="knowledge-icon"
                  style={{
                    background: item.color,
                  }}
                >
                  <i className={item.icon}></i>
                </div>

                <h4>{item.title}</h4>

                <p>{item.total}</p>
              </div>
            ))}
          </div>

          <div className="faq-list">
            {faqs.map((faq, index) => (
              <details key={index} className="faq-item">
                <summary>
                  {faq.question}

                  <i className="fa-solid fa-plus"></i>
                </summary>

                <p>{faq.answer}</p>
              </details>
            ))}
          </div>
        </div>
      </section>

      {/* ======================================================
    SUPPORT PROMISE
====================================================== */}

      <section className="support-promise">
        <div className="container">
          <div className="support-promise-wrapper">
            <div className="support-promise-left">
              <span className="promise-tag">WHY CHOOSE NEXGEN</span>

              <h2>More Than Support. A Long-Term Technology Partner.</h2>

              <p>
                At NexGen Web Designs, we don't just solve technical problems.
                We help businesses build, improve and grow their online presence
                through reliable support, modern technology and clear
                communication.
              </p>

              <div className="promise-stats">
                <div>
                  <h3>
                    {counters.projectsCount < 10
                      ? `0${counters.projectsCount}`
                      : counters.projectsCount}
                    +
                  </h3>

                  <span>Projects Delivered</span>
                </div>

                <div>
                  <h3>98%</h3>

                  <span>Client Satisfaction</span>
                </div>

                <div>
                  <h3>24 hrs</h3>

                  <span>Average First Response</span>
                </div>
              </div>
            </div>

            <div className="support-promise-right">
              {supportPromises.map((item, index) => (
                <div className="promise-card" key={index}>
                  <div className="promise-icon">
                    <i className={item.icon}></i>
                  </div>

                  <div>
                    <h4>{item.title}</h4>

                    <p>{item.text}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>
      {/* ======================================================
        FINAL SUPPORT CTA
====================================================== */}

      <section className="support-final-cta">
        <div className="container">
          <div className="support-final-card">
            {/* Background */}

            <div className="support-circle circle-one"></div>
            <div className="support-circle circle-two"></div>
            <div className="support-circle circle-three"></div>

            {/* Content */}

            <div className="support-final-content">
              <span>
                <i className="fa-solid fa-headset"></i>
                ALWAYS HERE TO HELP
              </span>

              <h2>Let's Build Something Amazing Together.</h2>

              <p>
                Whether you're starting a brand-new business, redesigning an
                existing website, or need professional technical support, our
                team is ready to help you move forward with confidence.
              </p>

              <div className="support-final-buttons">
                <Link to="/contact" className="support-final-primary">
                  Start Your Project
                  <i className="fa-solid fa-arrow-right"></i>
                </Link>

                <a
                  href={whatsappLink1}
                  target="_blank"
                  rel="noreferrer"
                  className="support-final-secondary"
                >
                  <i className="fa-brands fa-whatsapp"></i>
                  Chat on WhatsApp
                </a>
              </div>

              <div className="support-response">
                <div>
                  <i className="fa-solid fa-clock"></i>
                  Average Response
                  <strong>2 Hours</strong>
                </div>

                <div>
                  <i className="fa-solid fa-shield"></i>
                  Secure Communication
                  <strong>100%</strong>
                </div>

                <div>
                  <i className="fa-solid fa-user-group"></i>
                  Happy Clients
                  <strong>
                    {counters.projectsCount < 10
                      ? `0${counters.projectsCount}`
                      : counters.projectsCount}
                    +
                  </strong>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </main>
  );
};

export default Support;
